### ISSUE TITLE
Show description of pages on the homepage

### ISSUE THREAD

**Issue by africancup** [qdzhang/hugo-notepadium-mod#11]
This is more of a suggestion/ question. If I add a page with a `description` in the frontmatter, how can I make that description show in the homepage, instead of the content of the page?

**Comment by qdzhang** [comment]
Hugo provides an exclusive frontmatter variable `summary`, everything written in `summary` will show in the homepage rather than the text that starts the article. [There](https://gohugo.io/content-management/summaries/#front-matter-summary) are more details about `summary`.

And also, if you still want to use `description` to summarize an article, replace every "`Summary`" in [this line](https://github.com/qdzhang/hugo-notepadium-mod/blob/e1d178832f6132d7221b21cb776d39100e4d4617/layouts/partials/note-list.html#L10) with "`Description`".

**Comment by africancup** [comment]
Thank you very much for explaining this to me so thoroughly! The summary variable worked great, I should have done some more research before creating this issue 😅
