### ISSUE TITLE
How to remove "about" and "archive" from the homepage？

### ISSUE THREAD

**Issue by mxarcher** [qdzhang/hugo-notepadium-mod#14]
hello

![图片](https://user-images.githubusercontent.com/44336929/125944114-2b31f17c-dd1d-41c5-87f6-fb7c12d80768.png)
On the demo live, I found these on homepage. Do you know how to remove these?

when i use hugo-notepadium, it doesn't appear.

**Comment by qdzhang** [comment]
Fixed in 36ed27ef2c4d4f1cb74194086bc89cb7f3f65c0f.

If you want to hide any other page on homepage, add `hidden = true` in the frontmatter before the particular page.

**Comment by mxarcher** [comment]
@qdzhang it works for me, tks
but when I use `git pull` to update the theme, it doesn't work. 
I find there are two ways to update submodule
1. `cd theme/hugo-notepadium-mod/ && git pull origin main`
2. `git submodule foreach git pull origin main` 

and the latter is better.
so I think you could put it in the README.

**Comment by qdzhang** [comment]
`git pull` should be used in a **submodule directory**, as your first way does. When using `git pull` in the root directory, it will pull the main repository but not the submodule. Maybe I need to update the README, thank you for pointing out this. 

And  if you have other themes or git submodules, the second way will do `git pull` for all git submodules.

I'll close this issue because of problem solved. You could open new issues or pull requests if you have other problems.
